# Generated by Django 4.2.14 on 2024-07-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('allocation_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], max_length=10)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biweekly_income', models.FloatField()),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=10)),
                ('remaining_balance', models.FloatField()),
                ('categories', models.ManyToManyField(related_name='allocations', to='budget.category')),
            ],
        ),
    ]
